services:
    entity.form.registration:
        class: EntityBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: entitybundle_userregistration } 
            # alias = you get from your form function getname()

    entity.form.profile:
        class: EntityBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: entitybundle_userprofile } 
